project:
  type: website
  output-dir: docs

website:
  title: "天然产物数据库介绍"
  navbar:
    search: true
    title: false
    left:
      - href: 薰衣草.qmd
        text: 天然产物产品检索
      - href: 化合物.qmd
        text: 天然产物检索
      - href: about.qmd
        text: About
  
format:
  html:
    theme: cosmo
    toc: true

editor: visual