---
title: "BF"
format: html
editor: visual
---

## 基本信息

品牌：Base Formula

香气家族：花香

香调：中调

气味： 一种清新、甜美、草本、花香的香气

外观：N/A

建议用途：薰衣草油具有恢复、滋补的效果，是一种流行的缓解头部紧张的香薰油。它也常用于治疗混合舒缓关节和肌肉。薰衣草(法国)精油具有防腐性能，对皮肤有舒缓和滋养作用。它有助于调节和恢复皮肤活力，并有助于解决一系列皮肤问题，包括痤疮、油性皮肤、头皮屑、湿疹、烧伤、伤口、昆虫叮咬和蜇伤。它也是一种有效的驱虫剂。薰衣草油具有缓解疼痛的特性，对头痛、肌肉疼痛(尤其是与运动有关的疼痛)、风湿病和关节炎都有好处。这种油的抗病毒特性对感冒和流感也有帮助。

拉丁文命名：Lavandula angustifolia

品种：薰衣草

国家：法国

地区：N/A

经度：N41.3°-51.1°

纬度：E-5.0°-9.5°

培育方法：有机认证

提取方法：蒸馏提取

提取部位：薰衣草灌木的蓝色开花穗状花序

方法：精油

种类及含量：N/A

一般用药部位：薰衣草灌木的蓝色开花穗状花序

中医药：植物药

中医药功效：在薰衣草中，安神是一种重要功效，它所含的药用成分可以直接作用于人的中枢神经，既能舒缓神经，又能镇静安神，可作为一种催眠作用，平时将他制成植物精油，可用于人类失眠的预防和治疗，入药后可治疗人类神经衰弱和失眠。另外，薰衣草还含有多种天然抗菌消炎成分。另外，薰衣草中还含有甲醇提取物，能抑制脂质的过氧化，从而起到一定的抗衰老作用。在中医学看来，薰衣草具有解热镇痛、通经活血等功效，对高血压、高血脂等疾病也能起到很好的治疗作用，而且还能缓解女性由于淤血引起的痛经，减轻疼痛症状。

其他民族医药：维吾尔族用药材

其他民族医药功效：维吾尔医学认为薰衣草性质为二级湿热面积有消散寒气、燥湿止痛、补胃理脑的功效,在胸腹胀满、感冒咳嗽、头晕头痛、关节骨痛及心悸气短等疾病的治疗中均有所应用。

芳疗：用于芳疗中的熏蒸法，按摩法，沐浴法

芳疗功效：熏蒸法：此法可有效地安抚情绪、愉悦心情，避免失眠、增加记忆、净化空气等。按摩法：按一定比例调制按摩精油进行全身按摩，可以有效地美容护肤，放松机体，回归自然。沐浴法：通过SPA,可彻底解除疲劳、调理技能，治疗或改善神经衰弱、焦虑沮丧、神经紧张等症状，提高睡眠，减少治疗肌肉疼痛，效果显著。

其他：在乳液中加入薰衣草，薰衣草1滴+适量凡士林

其他功效：干裂修复，嘴唇保养，消痛止痒，清热解毒：薰衣草味辛，性寒，能够起到清热解毒的作用，辅助治疗口舌生疮、发热、风疹等病症。

链接：<https://www.baseformula.com/lavender-french-essential-oil?search=lavender>

COA(GC analysis)：
