---
title: "PP"
format: html
editor: visual
---

## 基本信息

品牌：Perfect Potion

香气家族：N/A

香调：N/A

气味：一种清新的花香气味，带有草本、甜香，以及香脂和木质的底调

外观：无色或淡黄色的油状物

建议用途：薰衣草对神经系统有协调作用。它可以缓解焦虑、压力和神经紧张，促进宁静、平静和愈合。

拉丁文命名：Lavandula angustifolia

品种：薰衣草

国家：保加利亚

地区：N/A

经度：N41.2°-44.2°

纬度：E22.4°-28.6°

培育方法：有机认证

提取方法：蒸馏提取

提取部位：花顶部

方法：纯精油

种类及含量：a-蒎烯(0.02-0.67%)、柠檬烯(0.02-0.68%)、1,8-桉树脑(0.01-0.21%)、顺-辛烯(1.35-2.87%)、反-辛烯(0.86-1.36%)、3-辛酮(1.75- 3.04%)、樟脑(0.54-0.89%)、芳樟醇(29.35-41.62%)、乙酸芳樟烯(46.71-53.80%)、石竹烯(2.64-5.05%)、松油烯-4-醇(0.03-4.16%)、乙酸薰衣草烯(0.27-4.24%)。

一般用药部位：花顶部

中医药：植物药

中医药功效：在薰衣草中，安神是一种重要功效，它所含的药用成分可以直接作用于人的中枢神经，既能舒缓神经，又能镇静安神，可作为一种催眠作用，平时将他制成植物精油，可用于人类失眠的预防和治疗，入药后可治疗人类神经衰弱和失眠。另外，薰衣草还含有多种天然抗菌消炎成分。另外，薰衣草中还含有甲醇提取物，能抑制脂质的过氧化，从而起到一定的抗衰老作用。在中医学看来，薰衣草具有解热镇痛、通经活血等功效，对高血压、高血脂等疾病也能起到很好的治疗作用，而且还能缓解女性由于淤血引起的痛经，减轻疼痛症状。

其他民族医药：维吾尔族用药材

其他民族医药功效：维吾尔医学认为薰衣草性质为二级湿热面积有消散寒气、燥湿止痛、补胃理脑的功效,在胸腹胀满、感冒咳嗽、头晕头痛、关节骨痛及心悸气短等疾病的治疗中均有所应用。

芳疗：用于芳疗中的熏蒸法，按摩法，沐浴法

芳疗功效：熏蒸法：此法可有效地安抚情绪、愉悦心情，避免失眠、增加记忆、净化空气等。按摩法：按一定比例调制按摩精油进行全身按摩，可以有效地美容护肤，放松机体，回归自然。沐浴法：通过SPA,可彻底解除疲劳、调理技能，治疗或改善神经衰弱、焦虑沮丧、神经紧张等症状，提高睡眠，减少治疗肌肉疼痛，效果显著。

其他：在乳液中加入薰衣草，薰衣草6滴+适量凡士林

其他功效：干裂修复，嘴唇保养，消痛止痒，清热解毒：薰衣草味辛，性寒，能够起到清热解毒的作用，辅助治疗口舌生疮、发热、风疹等病症。

链接：<https://www.perfectpotion.com.au/products/lavender-certified-organic?_pos=1&_sid=93ad81fe8&_ss=r&_fid=14283ed88>

COA(GC analysis)：
